name = "jiobase-api"
main = "src/index.ts"
compatibility_date = "2025-02-27"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "api.jiobase.com/*", zone_name = "jiobase.com" }
]

[[d1_databases]]
binding = "DB"
database_name = "jiobase-db"
database_id = "f3c420b4-f034-4dcd-8aaa-2af9991df82a"
migrations_dir = "drizzle"

[[kv_namespaces]]
binding = "PROXY_CONFIG"
id = "7ab7e07aa2ae4cada455bd45e59efa14"

[vars]
ENVIRONMENT = "production"
APP_URL = "https://app.jiobase.com"
